### ISSUE TITLE
assembly metadata

### ISSUE THREAD

**Issue by hubmayr** [chw3k5/WaferScreen#1]
Implement assembly metadata from 

https://docs.google.com/spreadsheets/d/1PstobJfm8kcSz5q2NL82ZyRZcIQQWGjjK8aEDxX0Chc/edit?usp=drive_web&ouid=114479652919019582297

in order to map screening data to a unique chip identifier.

**Comment by chw3k5** [comment]
Reported fixed by Zach and not committed.

**Comment by chw3k5** [comment]
I am supposing this is no longer and issue and that a work around was found.
