### ISSUE TITLE
Metric to quantify "weird v-phi"

### ISSUE THREAD

**Issue by hubmayr** [chw3k5/WaferScreen#2]
Report a metric that quantifies if a flux-response has the sharp peaks in the v-phi response.  Suggest reporting the chi-squared of lambda fit.

**Comment by chw3k5** [comment]
chi-square only tells you that the data deviates from the model. So it will be indistinguishable from the other common errors, like the poor-fits of double resonators. Further, chi-squared is guaranteed to trace linearly with the yet-unquantified v-phi weirdness. I would suggest using principle component analysis, Subtract the model from the data, look at what remains. From this a classification system could be developed, the v-phi weirdness will look like a wave packet, fit the wave packet, use the amplitude of the wave packet as a fair descriptor of the amount  v-phi weirdness.

Perhaps you should open a new issues request and simply request a chi-squared. This larger issue will take longer and is probably the subject for research paper.

**Comment by chw3k5** [comment]
chi square has been implemented. Contest have been added by also plotting the lambda fits residuals on the rug plot frame.
