### ISSUE TITLE
lambda corrected dfpp

### ISSUE THREAD

**Issue by hubmayr** [chw3k5/WaferScreen#3]
Write software to produce a plot of lambda corrected dfpp (ie "flux ramp span" in ScatterHist)

lambda_corrected_dfpp = dfpp*(1-lambda^2)/lambda.  Note this metric removes the contribution from Ic variations.

**Comment by chw3k5** [comment]
Please confirm the dfpp is a scaler and define the acronym. This will information will help to make the resulting code more readable.

**Comment by hubmayr** [comment]
dfpp is the "delta frequency peak to peak", it is identical to "flux ramp span".

**Comment by chw3k5** [comment]
Done.
