### ISSUE TITLE
add unique chip ID to report plot

### ISSUE THREAD

**Issue by hubmayr** [chw3k5/WaferScreen#5]
In upper right summary text of report plot, add chip ID: Wafer # (x_position, y_position)

**Comment by chw3k5** [comment]
This was always going to be something that was added. If you have comments about plot  design and layout, collect them over a period of weeks and present them all at once. If this forum is flooded with small unrelated issues if will cease to be useful.

**Comment by chw3k5** [comment]
It was fixed in the latest commit, without me ever reading this.
